# -*- coding: utf-8 -*-
"""Project-Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DV9qxjP3AVNu05XHrjWmnt13fg_y2f4i

**Group Members: Anees Ahmed & Mubashir Iqbal Course: Computer Vision**
"""

# CELL 1 — MOUNT DRIVE & SET PATHS
import os
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

ZIP_PATH    = "/content/drive/MyDrive/bird_dataset/archive.zip"
WORKDIR     = "/content/bird_project"
EXTRACT_DIR = WORKDIR + "/raw"
os.makedirs(EXTRACT_DIR, exist_ok=True)

BEST_PATH    = "/content/drive/MyDrive/bird_dataset/bird_model_best.keras"
LATEST_PATH  = "/content/drive/MyDrive/bird_dataset/bird_model_latest.keras"
HISTORY_DIR  = "/content/drive/MyDrive/bird_dataset/history"
os.makedirs(HISTORY_DIR, exist_ok=True)

print("Drive mounted")
print("Working dir :", WORKDIR)
print("Best model  :", BEST_PATH)
print("Latest model:", LATEST_PATH)
print("ZIP exists  :", os.path.exists(ZIP_PATH))

import zipfile
import tarfile
import shutil
import os
from pathlib import Path

CUB_DIR = os.path.join(EXTRACT_DIR, "CUB_200_2011")

if (os.path.exists(CUB_DIR) and
        os.path.exists(f"{CUB_DIR}/images.txt") and
        os.path.exists(f"{CUB_DIR}/images")):
    img_count = len(list(Path(f"{CUB_DIR}/images").rglob("*.jpg")))
    print("Already extracted — skipping")
    print(f"CUB DIR  : {CUB_DIR}")
    print(f"Images   : {img_count} jpg files")
else:
    print("Extracting from scratch...")
    if os.path.exists(EXTRACT_DIR):
        shutil.rmtree(EXTRACT_DIR)
    os.makedirs(EXTRACT_DIR, exist_ok=True)

    print("Extracting archive.zip ...")
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(EXTRACT_DIR)
    print("ZIP extracted")

    for tgz_name in ["CUB_200_2011.tgz", "segmentations.tgz"]:
        tgz_path = os.path.join(EXTRACT_DIR, tgz_name)
        if os.path.exists(tgz_path):
            print(f"Extracting {tgz_name} ...")
            try:
                with tarfile.open(tgz_path, 'r:gz') as t:
                    t.extractall(EXTRACT_DIR, filter='data')
            except TypeError:
                with tarfile.open(tgz_path, 'r:gz') as t:
                    t.extractall(EXTRACT_DIR)
            print(f"{tgz_name} done")

print(f"\nCUB_DIR = {CUB_DIR}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df_images = pd.read_csv(f"{CUB_DIR}/images.txt",
                        sep=' ', header=None, names=['id', 'relpath'])
df_labels = pd.read_csv(f"{CUB_DIR}/image_class_labels.txt",
                        sep=' ', header=None, names=['id', 'label'])
df_split  = pd.read_csv(f"{CUB_DIR}/train_test_split.txt",
                        sep=' ', header=None, names=['id', 'is_train'])

df = df_images.merge(df_labels, on='id').merge(df_split, on='id')
df['filepath'] = df['relpath'].apply(lambda p: f"{CUB_DIR}/images/{p}")
df['label']    = df['label'] - 1

class_names = []
with open(f"{CUB_DIR}/classes.txt") as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) >= 2:
            class_names.append(parts[1])
num_classes = len(class_names)

train_df, temp_df = train_test_split(
    df, test_size=0.20, random_state=42, stratify=df['label'])
val_df, test_df = train_test_split(
    temp_df, test_size=0.50, random_state=42, stratify=temp_df['label'])

train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)
val_df   = val_df.sample(frac=1,   random_state=42).reset_index(drop=True)
test_df  = test_df.sample(frac=1,  random_state=42).reset_index(drop=True)

print("=" * 45)
print(f"Total   : {len(df)}")
print(f"Train   : {len(train_df)} (80%)")
print(f"Val     : {len(val_df)} (10%)")
print(f"Test    : {len(test_df)} (10%)")
print(f"Classes : {num_classes}")
print("=" * 45)

