# -*- coding: utf-8 -*-
"""Project-Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DV9qxjP3AVNu05XHrjWmnt13fg_y2f4i

**Group Members: Anees Ahmed & Mubashir Iqbal Course: Computer Vision**
"""

# CELL 1 — MOUNT DRIVE & SET PATHS
import os
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

ZIP_PATH    = "/content/drive/MyDrive/bird_dataset/archive.zip"
WORKDIR     = "/content/bird_project"
EXTRACT_DIR = WORKDIR + "/raw"
os.makedirs(EXTRACT_DIR, exist_ok=True)

BEST_PATH    = "/content/drive/MyDrive/bird_dataset/bird_model_best.keras"
LATEST_PATH  = "/content/drive/MyDrive/bird_dataset/bird_model_latest.keras"
HISTORY_DIR  = "/content/drive/MyDrive/bird_dataset/history"
os.makedirs(HISTORY_DIR, exist_ok=True)

print("Drive mounted")
print("Working dir :", WORKDIR)
print("Best model  :", BEST_PATH)
print("Latest model:", LATEST_PATH)
print("ZIP exists  :", os.path.exists(ZIP_PATH))

import zipfile
import tarfile
import shutil
import os
from pathlib import Path

CUB_DIR = os.path.join(EXTRACT_DIR, "CUB_200_2011")

if (os.path.exists(CUB_DIR) and
        os.path.exists(f"{CUB_DIR}/images.txt") and
        os.path.exists(f"{CUB_DIR}/images")):
    img_count = len(list(Path(f"{CUB_DIR}/images").rglob("*.jpg")))
    print("Already extracted — skipping")
    print(f"CUB DIR  : {CUB_DIR}")
    print(f"Images   : {img_count} jpg files")
else:
    print("Extracting from scratch...")
    if os.path.exists(EXTRACT_DIR):
        shutil.rmtree(EXTRACT_DIR)
    os.makedirs(EXTRACT_DIR, exist_ok=True)

    print("Extracting archive.zip ...")
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(EXTRACT_DIR)
    print("ZIP extracted")

    for tgz_name in ["CUB_200_2011.tgz", "segmentations.tgz"]:
        tgz_path = os.path.join(EXTRACT_DIR, tgz_name)
        if os.path.exists(tgz_path):
            print(f"Extracting {tgz_name} ...")
            try:
                with tarfile.open(tgz_path, 'r:gz') as t:
                    t.extractall(EXTRACT_DIR, filter='data')
            except TypeError:
                with tarfile.open(tgz_path, 'r:gz') as t:
                    t.extractall(EXTRACT_DIR)
            print(f"{tgz_name} done")

print(f"\nCUB_DIR = {CUB_DIR}")