# -*- coding: utf-8 -*-
"""Project-Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DV9qxjP3AVNu05XHrjWmnt13fg_y2f4i

**Group Members: Anees Ahmed & Mubashir Iqbal Course: Computer Vision**
"""

# CELL 1 — MOUNT DRIVE & SET PATHS
import os
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

ZIP_PATH    = "/content/drive/MyDrive/bird_dataset/archive.zip"
WORKDIR     = "/content/bird_project"
EXTRACT_DIR = WORKDIR + "/raw"
os.makedirs(EXTRACT_DIR, exist_ok=True)

print(" Drive mounted")
print(" Working dir :", WORKDIR)
print(" Extract dir :", EXTRACT_DIR)
print(" ZIP path    :", ZIP_PATH)
print(" ZIP exists  :", os.path.exists(ZIP_PATH))

# CELL 2 — SMART EXTRACTION (handles partial extraction)
import zipfile, tarfile, shutil, os
from pathlib import Path

CUB_DIR = os.path.join(EXTRACT_DIR, "CUB_200_2011")

if os.path.exists(CUB_DIR) and os.path.exists(f"{CUB_DIR}/images.txt") and \
   os.path.exists(f"{CUB_DIR}/images"):
    print(" CUB_200_2011 already fully extracted — skipping everything")
    print(f" CUB DIR : {CUB_DIR}")
    print(f" Contents: {os.listdir(CUB_DIR)}")
    img_count = len(list(Path(f"{CUB_DIR}/images").rglob("*.jpg")))
    print(f"  Images  : {img_count} jpg files found")

else:
    print("Full extraction needed...")

    # Clean any partial extraction to start fresh
    if os.path.exists(EXTRACT_DIR):
        print("Removing partial extraction...")
        shutil.rmtree(EXTRACT_DIR)
    os.makedirs(EXTRACT_DIR, exist_ok=True)
    print(" Clean directory created")


    print("\nStep 1: Extracting archive.zip ...")
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(EXTRACT_DIR)
    print("archive.zip extracted")
    print(f"Contents after ZIP: {os.listdir(EXTRACT_DIR)}")

    tgz1 = os.path.join(EXTRACT_DIR, "CUB_200_2011.tgz")
    if os.path.exists(tgz1):
        print(f"\n Step 2: Extracting CUB_200_2011.tgz ...")
        print(f"   File size: {os.path.getsize(tgz1) / 1e6:.1f} MB")
        try:
            with tarfile.open(tgz1, 'r:gz') as t:
                t.extractall(EXTRACT_DIR, filter='data')
            print(" CUB_200_2011.tgz extracted")
        except TypeError:
            # Older Python — filter param not supported
            with tarfile.open(tgz1, 'r:gz') as t:
                t.extractall(EXTRACT_DIR)
            print("CUB_200_2011.tgz extracted (no filter)")
        except EOFError as e:
            print(f"EOFError on CUB tgz: {e}")
            print("ZIP file on Drive may be corrupted — try re-uploading")
    else:
        print(f"CUB_200_2011.tgz not found in ZIP")


    tgz2 = os.path.join(EXTRACT_DIR, "segmentations.tgz")
    if os.path.exists(tgz2):
        print(f"\n Step 3: Extracting segmentations.tgz ...")
        try:
            with tarfile.open(tgz2, 'r:gz') as t:
                t.extractall(EXTRACT_DIR, filter='data')
            print(" segmentations.tgz extracted")
        except TypeError:
            with tarfile.open(tgz2, 'r:gz') as t:
                t.extractall(EXTRACT_DIR)
            print(" segmentations.tgz extracted (no filter)")
        except EOFError as e:
            print(f"  segmentations.tgz error (non-critical): {e}")
    else:
        print("segmentations.tgz not found (non-critical)")

    CUB_DIR = os.path.join(EXTRACT_DIR, "CUB_200_2011")
    if os.path.exists(CUB_DIR) and os.path.exists(f"{CUB_DIR}/images.txt"):
        img_count = len(list(Path(f"{CUB_DIR}/images").rglob("*.jpg")))
        print(f"\nCUB dataset ready!")
        print(f"Contents : {os.listdir(CUB_DIR)}")
        print(f"Images   : {img_count} jpg files")
    else:
        print("\nExtraction failed!")
        print("   Possible fix: re-upload archive.zip to Google Drive")

print(f"\nCUB_DIR = {CUB_DIR}")

# CELL 3 — LOAD METADATA & STRATIFIED SPLIT (80-10-10)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

ROOT = CUB_DIR

df_images = pd.read_csv(f"{ROOT}/images.txt",           sep=' ', header=None, names=['id','relpath'])
df_labels = pd.read_csv(f"{ROOT}/image_class_labels.txt", sep=' ', header=None, names=['id','label'])
df_split  = pd.read_csv(f"{ROOT}/train_test_split.txt",  sep=' ', header=None, names=['id','is_train'])

df = df_images.merge(df_labels, on='id').merge(df_split, on='id')
df['filepath'] = df['relpath'].apply(lambda p: f"{ROOT}/images/{p}")
df['label']    = df['label'] - 1

class_names = []
with open(f"{ROOT}/classes.txt") as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) >= 2:
            class_names.append(parts[1])

num_classes = len(class_names)

train_df, temp_df = train_test_split(df, test_size=0.20,
                                     random_state=42, stratify=df['label'])
val_df,  test_df  = train_test_split(temp_df, test_size=0.50,
                                     random_state=42, stratify=temp_df['label'])

train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)
val_df   = val_df.sample(frac=1,   random_state=42).reset_index(drop=True)
test_df  = test_df.sample(frac=1,  random_state=42).reset_index(drop=True)

total = len(df)
print("=" * 45)
print(f" Total images   : {total}")
print(f" Train          : {len(train_df):>5}  ({len(train_df)/total*100:.1f}%)")
print(f" Validation     : {len(val_df):>5}  ({len(val_df)/total*100:.1f}%)")
print(f" Test           : {len(test_df):>5}  ({len(test_df)/total*100:.1f}%)")
print(f" Num classes    : {num_classes}")
print(f" Example class  : {class_names[0]}")
print("=" * 45)

missing = train_df[~train_df['filepath'].apply(os.path.exists)]
print(f" Missing files  : {len(missing)}")

# CELL 4
# Fix: bypass EfficientNetV2 preprocess_input entirely
# Use manual normalization: pixel/255.0 → [0,1] range
# EfficientNetV2 works fine with [0,1] float32 input
import cv2
import tensorflow as tf
import numpy as np

IMG_SIZE   = 260
BATCH_SIZE = 16
AUTOTUNE   = tf.data.AUTOTUNE

tf.keras.mixed_precision.set_global_policy('mixed_float16')
print("Mixed precision:", tf.keras.mixed_precision.global_policy().name)


def apply_blur(img_np, severity=None):
    if severity is None:
        severity = np.random.uniform(1.0, 4.5)
    return cv2.GaussianBlur(img_np, (0, 0), sigmaX=severity)

def apply_noise(img_np, severity=None):
    if severity is None:
        severity = np.random.uniform(8, 45)
    noise = np.random.normal(0, severity, img_np.shape).astype(np.float32)
    return np.clip(img_np.astype(np.float32) + noise, 0, 255).astype(np.uint8)

def apply_darkness(img_np, severity=None):
    if severity is None:
        severity = np.random.uniform(0.20, 0.65)
    return np.clip(img_np.astype(np.float32) * severity, 0, 255).astype(np.uint8)

def apply_fog(img_np, severity=None):
    if severity is None:
        severity = np.random.uniform(0.30, 0.65)
    fog = np.ones_like(img_np, dtype=np.float32) * 255
    result = cv2.addWeighted(img_np.astype(np.float32),
                             1 - severity, fog, severity, 0)
    return np.clip(result, 0, 255).astype(np.uint8)

def apply_jpeg(img_np, severity=None):
    if severity is None:
        severity = int(np.random.randint(5, 35))
    _, enc = cv2.imencode('.jpg', img_np,
                          [int(cv2.IMWRITE_JPEG_QUALITY), severity])
    return cv2.imdecode(enc, cv2.IMREAD_COLOR)

def apply_random_degradation(img_np):
    """img_np is uint8 [0,255] — apply 1 to 3 random degradations"""
    degradations = [apply_blur, apply_noise,
                    apply_darkness, apply_fog, apply_jpeg]
    n = np.random.randint(1, 4)
    chosen = np.random.choice(degradations, size=n, replace=False)
    result = img_np.copy()
    for fn in chosen:
        result = fn(result)
    return result

def load_and_preprocess(path, label):
    """
    Load image → resize → normalize to [0, 1]
    All datasets use this same function for consistency
    """
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = tf.cast(img, tf.float32) / 255.0      # → [0.0, 1.0]
    return img, tf.one_hot(label, num_classes)

def standard_augment(img, label):
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_brightness(img, max_delta=0.1)
    img = tf.image.random_contrast(img, lower=0.9, upper=1.1)
    img = tf.clip_by_value(img, 0.0, 1.0)
    return img, label

def degrade_tf(img_tensor, label):
    """
    img_tensor is float32 [0,1]
    Convert to uint8 → degrade → convert back to [0,1]
    """
    def _degrade(img_np):
        img_uint8 = (img_np * 255.0).astype(np.uint8)
        degraded  = apply_random_degradation(img_uint8)
        return degraded.astype(np.float32) / 255.0

    result = tf.numpy_function(
        func=_degrade,
        inp=[img_tensor],
        Tout=tf.float32
    )
    result.set_shape([IMG_SIZE, IMG_SIZE, 3])
    return result, label

def make_dataset(df, training=False, degrade=False):
    paths  = df['filepath'].values
    labels = df['label'].values.astype(np.int32)

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        ds = ds.shuffle(buffer_size=len(df), seed=42)

    ds = ds.map(load_and_preprocess, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.map(standard_augment, num_parallel_calls=AUTOTUNE)
    if degrade:
        ds = ds.map(degrade_tf, num_parallel_calls=AUTOTUNE)

    return ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

def make_degraded_test(df, level='mild'):
    severity = {
        'mild':     dict(blur=1.0, noise=10,  dark=0.75, fog=0.20, jpeg=50),
        'moderate': dict(blur=2.5, noise=25,  dark=0.50, fog=0.45, jpeg=20),
        'severe':   dict(blur=4.5, noise=45,  dark=0.25, fog=0.65, jpeg=8),
    }[level]

    def _load_and_degrade(path, label):
        img = cv2.imread(path.decode())
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        img = apply_blur(img,     severity['blur'])
        img = apply_noise(img,    severity['noise'])
        img = apply_darkness(img, severity['dark'])
        img = apply_fog(img,      severity['fog'])
        img = apply_jpeg(img,     severity['jpeg'])

        img = img.astype(np.float32) / 255.0
        lbl = np.eye(num_classes)[int(label)]
        return img.astype(np.float32), lbl.astype(np.float32)

    def _wrap(path, label):
        img, lbl = tf.numpy_function(
            func=_load_and_degrade,
            inp=[path, label],
            Tout=[tf.float32, tf.float32]
        )
        img.set_shape([IMG_SIZE, IMG_SIZE, 3])
        lbl.set_shape([num_classes])
        return img, lbl

    ds = tf.data.Dataset.from_tensor_slices(
             (df['filepath'].values,
              df['label'].values.astype(np.int32)))
    return ds.map(_wrap, num_parallel_calls=AUTOTUNE)\
             .batch(BATCH_SIZE).prefetch(AUTOTUNE)


print("\nBuilding datasets...")

train_ds_clean   = make_dataset(train_df, training=True,  degrade=False)
train_ds         = make_dataset(train_df, training=True,  degrade=True)
val_ds           = make_dataset(val_df,   training=False, degrade=False)
test_ds          = make_dataset(test_df,  training=False, degrade=False)
test_ds_mild     = make_degraded_test(test_df, 'mild')
test_ds_moderate = make_degraded_test(test_df, 'moderate')
test_ds_severe   = make_degraded_test(test_df, 'severe')


print("\nVerifying all datasets...")
print("─" * 55)
all_ok = True
for name, ds in [("Train clean",    train_ds_clean),
                 ("Train degraded", train_ds),
                 ("Validation",     val_ds),
                 ("Test clean",     test_ds),
                 ("Test mild",      test_ds_mild),
                 ("Test moderate",  test_ds_moderate),
                 ("Test severe",    test_ds_severe)]:
    for x, y in ds.take(1):
        mn  = x.numpy().mean()
        mx  = x.numpy().max()
        std = x.numpy().std()
        ok  = 0.2 < mn < 0.8 and mx <= 1.01 and std > 0.1
        status = "✅" if ok else "❌"
        if not ok:
            all_ok = False
        print(f"  {status} {name:<20} mean={mn:.3f}  max={mx:.3f}  std={std:.3f}")
        break

print("─" * 55)
if all_ok:
    print("ALL DATASETS VERIFIED — ready to train!")
else:
    print("Some datasets still have issues — check ❌ rows")